const data = [
	{
		"id": 2,
		"title": "First Piece",
		"description": "Trying something new",
		"height": 3,
		"width": 8,
		"thickness": 0,
		"price": null,
		"forSale": false,
		"image": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.fLhpnaYJ1gtlB3THjW2x3wHaEK%26pid%3DApi%26h%3D160&f=1&ipt=79e15493708691e08084713eec93ecc75dde04da0d6e1d414438ef39694887ae&ipo=images",
		"notes": "hi",
		"CategoryId": 1,
	},
	{
		"id": 3,
		"title": "Dog Bone",
		"description": "This pices is made from tincan, bottlecaps and ulpostry nails mounted on 3/4\" plywood",
		"height": 8,
		"width": 8,
		"thickness": 0,
		"price": 190,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1684984440/pjuy8f68xrpu0hhc2dft.jpg",
		"notes": "this piece was recycled from an earlier piece called XXX",
		"CategoryId": 1,
	},
	{
		"id": 4,
		"title": "third Piece",
		"description": "medium description the quick brown fox jumped",
		"height": 19,
		"width": 10,
		"thickness": null,
		"price": 13,
		"forSale": true,
		"image": "https://images.squarespace-cdn.com/content/v1/521cdb27e4b046948f17852d/1590278309344-SAS104FP5W9VUKXOY92U/image-asset.jpeg?format=750w",
		"notes": "lots of notes lots of notes over the lazy cow the quick brown fox jumped over the lazy cow",
		"CategoryId": 1,
	},
	{
		"id": 6,
		"title": "dsfg",
		"description": "sdfg",
		"height": 2,
		"width": 1,
		"thickness": 1,
		"price": 1,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1682539288/sana4il95xeuxaopmfbn.jpg",
		"notes": "dsrg",
		"CategoryId": 1,
	},
	{
		"id": 8,
		"title": "Bi Planes Oranments",
		"description": "Tin cans",
		"height": 4,
		"width": 4,
		"thickness": 2,
		"price": 20,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1682965921/ten2y8yfdn49ail4yuys.jpg",
		"notes": "I like wonder woman",
		"CategoryId": 3
	},
	{
		"id": 9,
		"title": "Rise Coffee",
		"description": "Coffee, Chicken, Triangl, Text, Rise, Farm",
		"height": 14,
		"width": 14,
		"thickness": 0,
		"price": 425,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1683254952/elkv2auinqtmxxbluq8d.jpg",
		"notes": "Coffee, Chicken, Triangle, Text, Rise, Farm",
		"CategoryId": 1,
    "date": "4/3/2019"
	},
	{
		"id": 10,
		"title": "Fish Eye",
		"description": "Tin can, bottlecaps, nails on 3/4\" Plywood",
		"height": 6,
		"width": 14,
		"thickness": 0,
		"price": 225,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1683255699/a0sobojsqg0agw9tdblr.jpg",
		"notes": "",
		"CategoryId": 1,
    "date": "June 2021"
	},
	{
		"id": 12,
		"title": "upload picture from insta",
		"description": "",
		"height": 18,
		"width": 18,
		"thickness": 14,
		"price": 20,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1683255947/lrex5vfoed3olrkhdfm4.jpg",
		"notes": "",
		"CategoryId": 1,
    "oldPrice": 25
	},
	{
		"id": 13,
		"title": "Toy #2",
		"description": "super cool toy",
		"height": 3,
		"width": 2,
		"thickness": 1,
		"price": 8,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1685398630/pwzlakqca2l3rp089enk.jpg",
		"notes": "",
		"CategoryId": 3,
    "hours": 4
	},
	{
		"id": 14,
		"title": "new piece",
		"description": "I like this one",
		"height": 8,
		"width": 10,
		"thickness": 4,
		"price": 100,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1686450560/qih9lbjqgbhxswv9lhbv.jpg",
		"notes": "blau blau blau",
		"CategoryId": 1,
	},
	{
		"id": 14,
		"title": "plane",
		"description": "I like this one",
		"height": 8,
		"width": 10,
		"thickness": 4,
		"price": 100,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1686450560/qih9lbjqgbhxswv9lhbv.jpg",
		"notes": "blau blau blau",
		"CategoryId": 5,
	},
	{
		"id": 14,
		"title": "sculpture",
		"description": "I like this one",
		"height": 8,
		"width": 10,
		"thickness": 4,
		"price": 100,
		"forSale": true,
		"image": "https://res.cloudinary.com/dz815dbbu/image/upload/v1686450560/qih9lbjqgbhxswv9lhbv.jpg",
		"notes": "blau blau blau",
		"CategoryId": 2,
	}
]

module.exports = {data}